server:
  port: 8082
spring:
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    servlet:
      multipart:
        max-file-size: 1MB
        max-request-size: 1MB
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: theyaku
    driver-class-name: org.postgresql.Driver
  kafka:
    properties:
      sasl.mechanism: PLAIN
      sasl.jaas.config: >
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username='A2VCCYFEXERRJFK7'
        password='T1PRDVTCvX0z7sKX3daWHwJC0KS8rWIJwjKrsvIiMJkwEVqIWkEH8YQESlHSS4ni';
      security.protocol: SASL_SSL
      session.timeout.ms: 45000
    bootstrap-servers: pkc-ldvr1.asia-southeast1.gcp.confluent.cloud:9092
google:
  cloud:
    storage:
      bucket-name: theyaku-bucket11
      project-id: civil-hash-446108-e1
      project-name: theyaku
security:
  jwt:
    secret-key: theyakusecretkeysamirudinvidia1234567890123456
app:
  cors:
    allowed-origins: "http://localhost:3000"
