server:
  port: 8082
spring:
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update  # Automatically generate and update tables
    servlet:
      multipart:
        max-file-size: 1MB
        max-request-size: 1MB
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: theyaku
    driver-class-name: org.postgresql.Driver
google:
  cloud:
    storage:
      bucket-name: theyaku-bucket11
      project-id: civil-hash-446108-e1
      project-name: theyaku
security:
  jwt:
    secret-key: theyakusecretkeysamirudinvidia1234567890123456

