spring:
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/multi-warehouse?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: theyaku
    driver-class-name: org.postgresql.Driver
    schema: classpath:init-schema.sql