server:
  port: 8081
spring:
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc.time_zone: UTC  # Added to handle timezone settings
    hibernate:
      ddl-auto: update  # Automatically updates the database
    servlet:
      multipart:
        max-file-size: 1MB
        max-request-size: 1MB
  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: theyaku
    driver-class-name: org.postgresql.Driver
google:
  cloud:
    storage:
      bucket-name: theyaku-bucket11
      project-id: civil-hash-446108-e1
      project-name: theyaku
